#!/usr/bin/env sh

# Copyright 2015 the original authors.
# Gradle startup script for POSIX generated by Gradle.

DIR="`dirname "$0"`"
APP_BASE_NAME=`basename "$0"`
APP_HOME=`cd "$DIR"; pwd`

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    else
        echo "Gradle wrapper JAR not found. Install Gradle or regenerate the wrapper (gradle wrapper)." >&2
        exit 1
    fi
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "true" ] || [ "$msys" = "true" ] ; then
    JAVACMD=`cygpath --unix "$JAVACMD"`
fi

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
